const prisma = require('../config/db');

/**
 * Calculates next occurrence date safely handling month-end bounds
 */
function getNextOccurrenceDate(currentDate, frequency) {
  const d = new Date(currentDate);
  const freq = (frequency || 'monthly').toLowerCase();

  if (freq === 'weekly') {
    d.setDate(d.getDate() + 7);
  } else if (freq === 'yearly') {
    d.setFullYear(d.getFullYear() + 1);
  } else {
    // monthly
    const targetMonth = d.getMonth() + 1;
    const originalDay = d.getDate();
    d.setMonth(targetMonth);
    // Handle overflow (e.g., Jan 31 -> Feb 28/29)
    if (d.getDate() !== originalDay) {
      d.setDate(0);
    }
  }
  return d;
}

const lastAutoGenMap = new Map();

/**
 * Auto-generates due transactions for a specific user idempotently
 */
const autoGenerateDueTransactions = async (userId) => {
  if (!userId) return [];

  const uid = Number(userId);
  const nowMs = Date.now();
  const lastRun = lastAutoGenMap.get(uid);

  // Throttle per-user auto-generation to prevent duplicate DB queries during parallel dashboard loads
  if (lastRun && (nowMs - lastRun < 10000)) {
    return [];
  }
  lastAutoGenMap.set(uid, nowMs);

  const now = new Date();
  const generatedTransactions = [];

  try {
    // Fetch all active recurring transactions due on or before current date
    const dueRecurring = await prisma.recurringTransaction.findMany({
      where: {
        userId: Number(userId),
        isPaused: false,
        nextOccurrence: {
          lte: now
        }
      }
    });

    for (const item of dueRecurring) {
      let currentNext = new Date(item.nextOccurrence);
      let isPaused = item.isPaused;

      while (
        currentNext <= now &&
        !isPaused &&
        (!item.endDate || currentNext <= new Date(item.endDate))
      ) {
        const dueDate = new Date(currentNext);

        // Check idempotency - ensure no transaction already exists for this recurring ID and date
        const existing = await prisma.transaction.findFirst({
          where: {
            userId: Number(userId),
            recurringId: item.id,
            date: dueDate
          }
        });

        if (!existing) {
          const newTx = await prisma.transaction.create({
            data: {
              title: item.title || `${item.category || 'Recurring'} Payment`,
              description: item.description
                ? `${item.description} (Auto-recurring)`
                : `Recurring payment for ${item.category || 'expense'}`,
              amount: Number(item.amount),
              type: item.type,
              category: item.category,
              date: dueDate,
              userId: Number(userId),
              recurringId: item.id
            }
          });
          generatedTransactions.push(newTx);
        }

        // Advance to next occurrence
        currentNext = getNextOccurrenceDate(currentNext, item.frequency);

        // Check if end date reached
        if (item.endDate && currentNext > new Date(item.endDate)) {
          isPaused = true;
          break;
        }
      }

      // Update recurring transaction record with advanced nextOccurrence
      await prisma.recurringTransaction.update({
        where: { id: item.id },
        data: {
          nextOccurrence: currentNext,
          isPaused: isPaused
        }
      });
    }

    return generatedTransactions;
  } catch (error) {
    console.error('Error auto-generating recurring transactions:', error);
    return [];
  }
};

module.exports = {
  autoGenerateDueTransactions,
  getNextOccurrenceDate
};
