const { getCalendarEvents } = require('../services/calendarService');
const { autoGenerateDueTransactions } = require('../services/recurringGenerator');

const getEvents = async (req, res) => {
  try {
    const userId = req.user.id;
    const { year, month } = req.query;

    // Trigger auto generation check for due recurring items
    await autoGenerateDueTransactions(userId);

    const data = await getCalendarEvents(userId, year, month);
    res.status(200).json(data);
  } catch (error) {
    console.error('Error fetching calendar events:', error);
    res.status(500).json({ error: error.message });
  }
};

module.exports = {
  getEvents
};
