const prisma = require('../config/db');
const { generateInsights } = require('../services/aiService');
const { autoGenerateDueTransactions } = require('../services/recurringGenerator');
const { calculateFinancialForecast } = require('../services/forecastingService');

const monthNames = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
];

/**
 * Controller to fetch AI Financial Insights for authenticated user
 */
const getAIInsights = async (req, res) => {
  try {
    const userId = req.user.id;

    // Process due recurring items first
    await autoGenerateDueTransactions(userId);

    // Fetch user details, transactions, category budgets, savings goals, and financial forecast
    const [user, transactions, categoryBudgets, savingsGoals, forecast] = await Promise.all([
      prisma.user.findUnique({
        where: { id: userId },
        select: { budget: true }
      }),
      prisma.transaction.findMany({
        where: { userId },
        orderBy: { date: 'desc' }
      }),
      prisma.categoryBudget.findMany({
        where: { userId }
      }),
      prisma.savingsGoal.findMany({
        where: { userId }
      }),
      calculateFinancialForecast(userId).catch(() => null)
    ]);

    // Handle empty transactions
    if (!transactions || transactions.length === 0) {
      return res.status(200).json({
        empty: true,
        message: 'No transaction data available for AI analysis yet.',
        insights: null,
        stats: {
          totalIncome: 0,
          totalExpenses: 0,
          netBalance: 0,
          savingsRate: 0,
          transactionCount: 0
        }
      });
    }

    // 1. Aggregations
    let totalIncome = 0;
    let totalExpenses = 0;

    const now = new Date();
    const currentYear = now.getFullYear();
    const currentMonth = now.getMonth();
    let currentMonthExpenses = 0;

    const categoryMap = new Map();
    const monthlyMap = new Map();

    transactions.forEach((t) => {
      const amt = Number(t.amount) || 0;
      const d = t.date ? new Date(t.date) : null;
      const isValidDate = d && !isNaN(d.getTime());

      if (t.type === 'income') {
        totalIncome += amt;
      } else if (t.type === 'expense') {
        totalExpenses += amt;

        // Current month expenses
        if (isValidDate && d.getFullYear() === currentYear && d.getMonth() === currentMonth) {
          currentMonthExpenses += amt;
        }

        // Category breakdown
        let cat = (t.category || '').trim();
        if (!cat) cat = 'Other';
        cat = cat.charAt(0).toUpperCase() + cat.slice(1);
        categoryMap.set(cat, (categoryMap.get(cat) || 0) + amt);
      }

      // Monthly trends
      if (isValidDate) {
        const year = d.getFullYear();
        const monthIdx = d.getMonth();
        const sortKey = `${year}-${String(monthIdx + 1).padStart(2, '0')}`;
        const monthLabel = `${monthNames[monthIdx]} ${year}`;

        if (!monthlyMap.has(sortKey)) {
          monthlyMap.set(sortKey, {
            month: monthLabel,
            sortKey,
            income: 0,
            expense: 0
          });
        }

        const entry = monthlyMap.get(sortKey);
        if (t.type === 'income') entry.income += amt;
        if (t.type === 'expense') entry.expense += amt;
      }
    });

    const netBalance = totalIncome - totalExpenses;
    const savingsRate =
      totalIncome > 0
        ? Number(Math.max(0, ((netBalance / totalIncome) * 100)).toFixed(1))
        : 0;

    // Category breakdown list
    const categoryBreakdown = Array.from(categoryMap.entries())
      .map(([category, amount]) => ({
        category,
        amount,
        percentage:
          totalExpenses > 0
            ? ((amount / totalExpenses) * 100).toFixed(1)
            : '0'
      }))
      .sort((a, b) => b.amount - a.amount);

    const highestCategory = categoryBreakdown.length > 0 ? categoryBreakdown[0] : null;

    // Monthly trends list sorted chronologically
    const monthlyTrends = Array.from(monthlyMap.values())
      .sort((a, b) => a.sortKey.localeCompare(b.sortKey))
      .map((m) => ({
        month: m.month,
        income: m.income,
        expense: m.expense,
        net: m.income - m.expense
      }));

    // Enrich category budgets with current month spending
    const categoryBudgetsStats = categoryBudgets.map((b) => {
      const catKey = b.category.trim().toLowerCase();
      const spent = categoryMap.get(catKey) || 0;
      const limit = Number(b.amount);
      const usagePct = Number(((spent / limit) * 100).toFixed(1));
      return {
        category: b.category,
        limit,
        spent,
        remaining: limit - spent,
        usagePct,
        status: usagePct >= 100 ? 'exceeded' : usagePct >= 90 ? 'warning' : usagePct >= 75 ? 'approaching' : 'healthy'
      };
    });

    // Enrich savings goals with target details
    const savingsGoalsStats = savingsGoals.map((g) => {
      const target = Number(g.targetAmount) || 0;
      const current = Number(g.currentAmount) || 0;
      const remaining = Math.max(0, target - current);
      const progressPct = Number(Math.min(100, (current / Math.max(1, target)) * 100).toFixed(1));
      return {
        name: g.name,
        targetAmount: target,
        currentAmount: current,
        remainingAmount: remaining,
        progressPct,
        targetDate: g.targetDate,
        isCompleted: current >= target
      };
    });

    const stats = {
      totalIncome,
      totalExpenses,
      netBalance,
      savingsRate,
      monthlyBudget: user?.budget || null,
      currentMonthExpenses,
      categoryBreakdown,
      highestCategory,
      monthlyTrends,
      categoryBudgets: categoryBudgetsStats,
      savingsGoals: savingsGoalsStats,
      transactionCount: transactions.length,
      avgExpense:
        monthlyTrends.length > 0
          ? Math.round(totalExpenses / monthlyTrends.length)
          : totalExpenses,
      forecast
    };

    // 2. Generate AI Insights via aiService
    const insights = await generateInsights(stats);

    return res.status(200).json({
      empty: false,
      stats,
      insights
    });
  } catch (error) {
    console.error('Error generating AI insights:', error);
    return res.status(500).json({
      error: 'Failed to generate AI financial insights.'
    });
  }
};

module.exports = {
  getAIInsights
};
