const prisma = require('../config/db');
const { autoGenerateDueTransactions } = require('../services/recurringGenerator');
const { calculateFinancialForecast } = require('../services/forecastingService');

// CREATE
const createRecurringTransaction = async (req, res) => {
  try {
    const {
      title,
      description,
      amount,
      type,
      category,
      frequency,
      startDate,
      endDate
    } = req.body;

    if (!amount || !type || !category) {
      return res.status(400).json({
        error: 'Amount, type, and category are required'
      });
    }

    const validFreqs = ['weekly', 'monthly', 'yearly'];
    const freq = validFreqs.includes((frequency || '').toLowerCase())
      ? frequency.toLowerCase()
      : 'monthly';

    const start = startDate ? new Date(startDate) : new Date();
    const nextOcc = new Date(start);

    const recurring = await prisma.recurringTransaction.create({
      data: {
        title: title || `${category} ${freq.charAt(0).toUpperCase() + freq.slice(1)}`,
        description,
        amount: Number(amount),
        type,
        category,
        frequency: freq,
        startDate: start,
        nextOccurrence: nextOcc,
        endDate: endDate ? new Date(endDate) : null,
        userId: req.user.id
      }
    });

    // Auto-check due transactions immediately
    await autoGenerateDueTransactions(req.user.id);

    res.status(201).json(recurring);
  } catch (error) {
    console.error('Error creating recurring transaction:', error);
    res.status(500).json({ error: error.message });
  }
};

// GET ALL
const getRecurringTransactions = async (req, res) => {
  try {
    // Process due items first
    await autoGenerateDueTransactions(req.user.id);

    const list = await prisma.recurringTransaction.findMany({
      where: {
        userId: req.user.id
      },
      orderBy: {
        createdAt: 'desc'
      }
    });

    res.status(200).json(list);
  } catch (error) {
    console.error('Error fetching recurring transactions:', error);
    res.status(500).json({ error: error.message });
  }
};

// UPDATE
const updateRecurringTransaction = async (req, res) => {
  try {
    const { id } = req.params;

    const existing = await prisma.recurringTransaction.findFirst({
      where: {
        id: Number(id),
        userId: req.user.id
      }
    });

    if (!existing) {
      return res.status(404).json({ error: 'Recurring transaction not found' });
    }

    const {
      title,
      description,
      amount,
      type,
      category,
      frequency,
      nextOccurrence,
      endDate,
      isPaused
    } = req.body;

    const updated = await prisma.recurringTransaction.update({
      where: { id: Number(id) },
      data: {
        title: title !== undefined ? title : existing.title,
        description: description !== undefined ? description : existing.description,
        amount: amount !== undefined ? Number(amount) : existing.amount,
        type: type || existing.type,
        category: category || existing.category,
        frequency: frequency ? frequency.toLowerCase() : existing.frequency,
        nextOccurrence: nextOccurrence ? new Date(nextOccurrence) : existing.nextOccurrence,
        endDate: endDate !== undefined ? (endDate ? new Date(endDate) : null) : existing.endDate,
        isPaused: isPaused !== undefined ? Boolean(isPaused) : existing.isPaused
      }
    });

    await autoGenerateDueTransactions(req.user.id);

    res.status(200).json(updated);
  } catch (error) {
    console.error('Error updating recurring transaction:', error);
    res.status(500).json({ error: error.message });
  }
};

// TOGGLE PAUSE / RESUME
const togglePauseRecurringTransaction = async (req, res) => {
  try {
    const { id } = req.params;

    const existing = await prisma.recurringTransaction.findFirst({
      where: {
        id: Number(id),
        userId: req.user.id
      }
    });

    if (!existing) {
      return res.status(404).json({ error: 'Recurring transaction not found' });
    }

    const updated = await prisma.recurringTransaction.update({
      where: { id: Number(id) },
      data: {
        isPaused: !existing.isPaused
      }
    });

    if (!updated.isPaused) {
      await autoGenerateDueTransactions(req.user.id);
    }

    res.status(200).json(updated);
  } catch (error) {
    console.error('Error toggling pause on recurring transaction:', error);
    res.status(500).json({ error: error.message });
  }
};

// DELETE
const deleteRecurringTransaction = async (req, res) => {
  try {
    const { id } = req.params;

    const existing = await prisma.recurringTransaction.findFirst({
      where: {
        id: Number(id),
        userId: req.user.id
      }
    });

    if (!existing) {
      return res.status(404).json({ error: 'Recurring transaction not found' });
    }

    await prisma.recurringTransaction.delete({
      where: { id: Number(id) }
    });

    res.status(200).json({ message: 'Recurring transaction deleted successfully' });
  } catch (error) {
    console.error('Error deleting recurring transaction:', error);
    res.status(500).json({ error: error.message });
  }
};

// GET UPCOMING COMMITMENTS & FINANCIAL FORECAST
const getForecastAndUpcoming = async (req, res) => {
  try {
    await autoGenerateDueTransactions(req.user.id);
    const forecast = await calculateFinancialForecast(req.user.id);
    res.status(200).json(forecast);
  } catch (error) {
    console.error('Error fetching forecast & upcoming commitments:', error);
    res.status(500).json({ error: error.message });
  }
};

module.exports = {
  createRecurringTransaction,
  getRecurringTransactions,
  updateRecurringTransaction,
  togglePauseRecurringTransaction,
  deleteRecurringTransaction,
  getForecastAndUpcoming
};
