const prisma = require('../config/db')
const { autoGenerateDueTransactions } = require('../services/recurringGenerator')

// CREATE
const createTransaction = async (req, res) => {

  try {

    const {
      amount,
      type,
      category,
      description,
      date
    } = req.body

    if (!amount || !type || !date) {

      return res.status(400).json({
        error: 'Amount, type and date required'
      })
    }

    const transaction =
      await prisma.transaction.create({
        data: {
          amount: Number(amount),
          type,
          category,
          description,
          date: new Date(date),
          userId: req.user.id
        }
      })

    res.status(201).json(transaction)

  } catch (error) {

    res.status(500).json({
      error: error.message
    })
  }
}

// GET ALL / SEARCH / FILTER / PAGINATE
const getTransactions = async (req, res) => {
  try {
    // Process due recurring items first
    await autoGenerateDueTransactions(req.user.id);

    const {
      search,
      type,
      category,
      dateRange,
      startDate,
      endDate,
      minAmount,
      maxAmount,
      recurringStatus,
      sortBy,
      page,
      limit
    } = req.query;

    const where = {
      userId: req.user.id
    };

    // 1. Search Query (Title, Description, Category, Amount)
    if (search && search.trim() !== '') {
      const trimmedSearch = search.trim();
      const numSearch = Number(trimmedSearch);
      const isNum = !isNaN(numSearch);

      where.OR = [
        { title: { contains: trimmedSearch, mode: 'insensitive' } },
        { description: { contains: trimmedSearch, mode: 'insensitive' } },
        { category: { contains: trimmedSearch, mode: 'insensitive' } },
        ...(isNum ? [{ amount: numSearch }] : [])
      ];
    }

    // 2. Transaction Type Filter
    if (type && type !== 'all') {
      where.type = type;
    }

    // 3. Category Filter
    if (category && category !== 'all') {
      where.category = { equals: category, mode: 'insensitive' };
    }

    // 4. Date Range Filter
    const now = new Date();
    if (dateRange && dateRange !== 'all') {
      let start, end;
      if (dateRange === 'today') {
        start = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        end = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999);
      } else if (dateRange === 'this_week') {
        const dayOfWeek = now.getDay();
        start = new Date(now.getFullYear(), now.getMonth(), now.getDate() - dayOfWeek);
        end = new Date(now.getFullYear(), now.getMonth(), now.getDate() + (6 - dayOfWeek), 23, 59, 59, 999);
      } else if (dateRange === 'this_month') {
        start = new Date(now.getFullYear(), now.getMonth(), 1);
        end = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
      } else if (dateRange === 'last_month') {
        start = new Date(now.getFullYear(), now.getMonth() - 1, 1);
        end = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999);
      } else if (dateRange === 'last_3_months') {
        start = new Date(now.getFullYear(), now.getMonth() - 3, 1);
        end = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
      } else if (dateRange === 'this_year') {
        start = new Date(now.getFullYear(), 0, 1);
        end = new Date(now.getFullYear(), 11, 31, 23, 59, 59, 999);
      } else if (dateRange === 'custom') {
        if (startDate) start = new Date(startDate);
        if (endDate) {
          end = new Date(endDate);
          end.setHours(23, 59, 59, 999);
        }
      }

      if (start || end) {
        where.date = {};
        if (start) where.date.gte = start;
        if (end) where.date.lte = end;
      }
    }

    // 5. Amount Range Filter
    if (minAmount !== undefined && minAmount !== '') {
      where.amount = { ...(where.amount || {}), gte: Number(minAmount) };
    }
    if (maxAmount !== undefined && maxAmount !== '') {
      where.amount = { ...(where.amount || {}), lte: Number(maxAmount) };
    }

    // 6. Recurring Status Filter
    if (recurringStatus === 'recurring') {
      where.recurringId = { not: null };
    } else if (recurringStatus === 'one_time') {
      where.recurringId = null;
    }

    // 7. Sorting Order
    let orderBy = { date: 'desc' };
    if (sortBy === 'oldest') {
      orderBy = { date: 'asc' };
    } else if (sortBy === 'highest') {
      orderBy = { amount: 'desc' };
    } else if (sortBy === 'lowest') {
      orderBy = { amount: 'asc' };
    }

    // Fetch all matching items for Filtered Summary calculation
    const allFiltered = await prisma.transaction.findMany({
      where,
      select: { id: true, amount: true, type: true }
    });

    let filteredIncome = 0;
    let filteredExpense = 0;
    allFiltered.forEach((t) => {
      if (t.type === 'income') filteredIncome += t.amount;
      else if (t.type === 'expense') filteredExpense += t.amount;
    });

    const filteredSummary = {
      count: allFiltered.length,
      income: filteredIncome,
      expense: filteredExpense,
      net: filteredIncome - filteredExpense
    };

    // 8. Pagination vs Full List
    const hasPaginationParams = page !== undefined || limit !== undefined || search !== undefined || type !== undefined || category !== undefined || dateRange !== undefined || minAmount !== undefined || maxAmount !== undefined || recurringStatus !== undefined || sortBy !== undefined;

    if (hasPaginationParams) {
      const pageNum = Math.max(1, parseInt(page) || 1);
      const limitNum = Math.max(1, parseInt(limit) || 20);
      const skip = (pageNum - 1) * limitNum;
      const totalPages = Math.ceil(allFiltered.length / limitNum) || 1;

      const transactions = await prisma.transaction.findMany({
        where,
        orderBy,
        skip,
        take: limitNum
      });

      return res.status(200).json({
        transactions,
        pagination: {
          total: allFiltered.length,
          page: pageNum,
          limit: limitNum,
          totalPages
        },
        filteredSummary
      });
    } else {
      // Default plain array output for simple calls (Dashboard, Analytics, Insights)
      const transactions = await prisma.transaction.findMany({
        where,
        orderBy
      });

      return res.status(200).json(transactions);
    }
  } catch (error) {
    console.error('Error fetching transactions:', error);
    res.status(500).json({
      error: error.message
    });
  }
};

// UPDATE
const updateTransaction = async (req, res) => {

  try {

    const { id } = req.params

    const existingTransaction =
      await prisma.transaction.findFirst({
        where: {
          id: Number(id),
          userId: req.user.id
        }
      })

    if (!existingTransaction) {

      return res.status(404).json({
        error: 'Transaction not found'
      })
    }

    const updatedTransaction =
      await prisma.transaction.update({
        where: {
          id: Number(id)
        },
        data: {
          amount: Number(req.body.amount),
          type: req.body.type,
          category: req.body.category,
          description: req.body.description,
          date: new Date(req.body.date)
        }
      })

    res.status(200).json(updatedTransaction)

  } catch (error) {

    res.status(500).json({
      error: error.message
    })
  }
}

// DELETE
const deleteTransaction = async (req, res) => {

  try {

    const { id } = req.params

    const existingTransaction =
      await prisma.transaction.findFirst({
        where: {
          id: Number(id),
          userId: req.user.id
        }
      })

    if (!existingTransaction) {

      return res.status(404).json({
        error: 'Transaction not found'
      })
    }

    await prisma.transaction.delete({
      where: {
        id: Number(id)
      }
    })

    res.status(200).json({
      message: 'Transaction deleted successfully'
    })

  } catch (error) {

    res.status(500).json({
      error: error.message
    })
  }
}

module.exports = {
  createTransaction,
  getTransactions,
  updateTransaction,
  deleteTransaction
}